name: my_env  # Измените имя (не используйте 'base')
channels:
  - conda-forge
  - defaults
dependencies:
  # Базовые зависимости
  - python=3.12.7
  - pip=24.2

  # Основные научные пакеты
  - numpy=1.26.4
  - pandas=2.2.2
  - scipy=1.13.1
  - matplotlib=3.9.2
  - seaborn=0.13.2

  # Jupyter экосистема
  - jupyter=1.0.0
  - jupyterlab=4.2.5
  - ipykernel=6.28.0
  - notebook=7.2.2

  # Системные зависимости для Mac
  - libcxx=17.0.6  # Актуальная версия для Python 3.12
  - appnope=0.1.3
  - openssl=3.0.16

  # pip-пакеты
  - pip:
      - catboost==1.2.8
      - category-encoders==2.8.1
      - colorlog==6.9.0
      - graphviz==0.20.3
      - nyoka==5.5.0
      - optuna==4.3.0
      - optuna-integration==4.3.0
      - pynndescent==0.5.13
      - scikit-learn==1.6.1
      - umap==0.1.1
      - umap-learn==0.5.7
      - xgboost==3.0.0
      - flask==4.57.0
      - fastapi==2.21.1
      - uvicorn == 0.34.2
      - Jinja2 ==3.1.6
      - python-multipart==0.0.20
      - imbalanced-learn==0.13.0

